// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBjFqd5bUjkcS1CTSRQK6pcitW3F1nY8',
    appId: '1:475924106327:web:4d14ce55f06e7d1635e712',
    messagingSenderId: '475924106327',
    projectId: 'migra-42b82',
    authDomain: 'migra-42b82.firebaseapp.com',
    storageBucket: 'migra-42b82.firebasestorage.app',
    measurementId: 'G-HKJ4Z7JFT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3NI1JBvBa_-rSY8upKrua-0_UgRI44No',
    appId: '1:475924106327:android:26d54cbff00add3c35e712',
    messagingSenderId: '475924106327',
    projectId: 'migra-42b82',
    storageBucket: 'migra-42b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pD4DN4Znzolid-Xuor1TyaNnVn6UVSA',
    appId: '1:475924106327:ios:fbb1d6edae613d3135e712',
    messagingSenderId: '475924106327',
    projectId: 'migra-42b82',
    storageBucket: 'migra-42b82.firebasestorage.app',
    iosBundleId: 'com.example.migraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pD4DN4Znzolid-Xuor1TyaNnVn6UVSA',
    appId: '1:475924106327:ios:fbb1d6edae613d3135e712',
    messagingSenderId: '475924106327',
    projectId: 'migra-42b82',
    storageBucket: 'migra-42b82.firebasestorage.app',
    iosBundleId: 'com.example.migraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBjFqd5bUjkcS1CTSRQK6pcitW3F1nY8',
    appId: '1:475924106327:web:4e97cd40efdfbb9635e712',
    messagingSenderId: '475924106327',
    projectId: 'migra-42b82',
    authDomain: 'migra-42b82.firebaseapp.com',
    storageBucket: 'migra-42b82.firebasestorage.app',
    measurementId: 'G-6GM8YTL1DY',
  );
}
